schema: graphql/schema.graphql
documents: graphql/**/*.graphql
extensions:
  codegen:
    overwrite: true
    generates:
      generated/graphql.ts:
        plugins:
          - typescript
          - typescript-operations
          - urql-introspection
          - typescript-urql:
              documentVariablePrefix: "Untyped"
          - typed-document-node
      generated/schema.graphql:
        plugins:
          - schema-ast
