onlyBuiltDependencies:
  - esbuild
  - sharp

blockExoticSubdeps: true
minimumReleaseAge: 1440 # 24h
minimumReleaseAgeExclude:
  - "next@15.5.26"
  - "@next/env@15.5.26"
  - "@next/swc-darwin-arm64@15.5.26"
  - "@next/swc-darwin-x64@15.5.26"
  - "@next/swc-linux-arm64-gnu@15.5.26"
  - "@next/swc-linux-arm64-musl@15.5.26"
  - "@next/swc-linux-x64-gnu@15.5.26"
  - "@next/swc-linux-x64-musl@15.5.26"
  - "@next/swc-win32-arm64-msvc@15.5.26"
  - "@next/swc-win32-x64-msvc@15.5.26"
trustPolicy: no-downgrade
trustPolicyExclude:
  - "semver@6.3.1"
