import type { NextPage } from "next";
import Head from "next/head";

import { useFetchTwelveProductsQuery } from "../generated/graphql";

const Home: NextPage = () => {
  const [{ data }] = useFetchTwelveProductsQuery();

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="text-white">Saleor App Template - Configuration</div>
        {JSON.stringify(data)}
      </main>
    </div>
  );
};

export default Home;
