import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className="px-8 py-32">
          <div className="grid gap-8 items-start justify-center">
            <div className="relative group">
              <div className="absolute -inset-0.5 bg-gradient-to-r from-blue-600 to-indigo-600 rounded-lg blur opacity-75 group-hover:opacity-100 transition duration-1000 group-hover:duration-200 animate-tilt"></div>
              <button className="relative px-7 py-4 bg-black rounded-lg leading-none flex items-center divide-x divide-gray-600">
                <span className="flex items-center space-x-5 text-xl">
                  <span className="pr-6 text-gray-100">Your new Saleor App</span>
                </span>
                <span className="pl-6 text-blue-400 group-hover:text-gray-100 transition duration-200">Learn more &rarr;</span>
              </button>
            </div>
          </div>
        </div>

        <div>
          <h3 className="text-xl font-semibold text-gray-100">Resources</h3>
        </div>

      </main>

      <footer className="flex justify-center items-center py-10 text-white border-t border-gray-600">
        <a
          href="https://saleor.io"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            Saleor
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
